--Chapter 12

UPDATE TABLE
SET COLUMN =
	(SELECT COLUMN
		FROM TABLE_B
		WHERE TABLE.COLUMN = TABLE_B.COLUMN)
WHERE EXISTS
		(SELECT COLUMN
			FROM TABLE_B
			WHERE TABLE.COLUMN = TABLE_B.COLUMN);


SELECT GEO_NAME,
	STATE_US_ABBREVIATION,
	P0010001
FROM US_COUNTIES_2010
WHERE P0010001 >=
		(SELECT PERCENTILE_CONT(.9) WITHIN GROUP (
																																												ORDER BY P0010001)
			FROM US_COUNTIES_2010)
ORDER BY P0010001 DESC
CREATE TABLE US_COUNTIES_2010_TOP10 AS
SELECT *
FROM US_COUNTIES_2010;


DELETE
FROM US_COUNTIES_2010_TOP10
WHERE P0010001 <
		(SELECT PERCENTILE_CONT(.9) WITHIN GROUP (
																																												ORDER BY P0010001)
			FROM US_COUNTIES_2010_TOP10);


SELECT ROUND(CALCS.AVERAGE,

								0) AS AVERAGE,
	CALCS.MEDIAN,
	ROUND(CALCS.AVERAGE - CALCS.MEDIAN,
		0) AS MEDIAN_AVERAGE_DIFF
FROM
	(SELECT AVG(P0010001) AS AVERAGE,
			PERCENTILE_CONT(.5) WITHIN GROUP (
																																					ORDER BY P0010001)::NUMERIC(10,

																																																										1) AS MEDIAN
		FROM US_COUNTIES_2010) AS CALCS;


SELECT CENSUS.STATE_US_ABBREVIATION AS ST,
	CENSUS.ST_POPULATION,
	PLANTS.PLANT_COUNT,
	ROUND((PLANTS.PLANT_COUNT / CENSUS.ST_POPULATION::NUMERIC(10,

																																																				1)) * 1000000,
		1) AS PLANTS_PER_MILLION
FROM
	(SELECT ST,
			COUNT(*) AS PLANT_COUNT
		FROM MEAT_POULTRY_EGG_INSPECT
		GROUP BY ST) AS PLANTS
JOIN
	(SELECT STATE_US_ABBREVIATION,
			SUM(P0010001) AS ST_POPULATION
		FROM US_COUNTIES_2010
		GROUP BY STATE_US_ABBREVIATION) AS CENSUS ON PLANTS.ST = CENSUS.STATE_US_ABBREVIATION
ORDER BY PLANTS_PER_MILLION DESC;


SELECT GEO_NAME,
	STATE_US_ABBREVIATION AS ST,
	P0010001 AS TOTAL_POP,

	(SELECT PERCENTILE_CONT(.5) WITHIN GROUP (
																																											ORDER BY P0010001)
		FROM US_COUNTIES_2010) AS US_MEDIAN
FROM US_COUNTIES_2010;


SELECT GEO_NAME,
	STATE_US_ABBREVIATION AS ST,
	P0010001 AS TOTAL_POP,

	(SELECT PERCENTILE_CONT(.5) WITHIN GROUP (
																																											ORDER BY P0010001)
		FROM US_COUNTIES_2010) AS US_MEDIAN,
	P0010001 -
	(SELECT PERCENTILE_CONT(.5) WITHIN GROUP (
																																											ORDER BY P0010001)
		FROM US_COUNTIES_2010) AS DIFF_FROM_MEDIAN
FROM US_COUNTIES_2010
WHERE (P0010001 -
								(SELECT PERCENTILE_CONT(.5) WITHIN GROUP (
																																																		ORDER BY P0010001)
									FROM US_COUNTIES_2010)) BETWEEN -1000 AND 1000;


SELECT FIRST_NAME,
	LAST_NAME
FROM EMPLOYEES
WHERE ID IN
		(SELECT ID
			FROM RETIREES);


SELECT FIRST_NAME,
	LAST_NAME
FROM EMPLOYEES
WHERE EXISTS
		(SELECT ID
			FROM RETIREES);


SELECT FIRST_NAME,
	LAST_NAME
FROM EMPLOYEES
WHERE EXISTS
		(SELECT ID
			FROM RETIREES
			WHERE ID = EMPLOYEES.ID);


SELECT FIRST_NAME,
	LAST_NAME
FROM EMPLOYEES
WHERE NOT EXISTS
		(SELECT ID
			FROM RETIREES
			WHERE ID = EMPLOYEES.ID);

WITH LARGE_COUNTIES (GEO_NAME,

							ST,
							P0010001) AS
	(SELECT GEO_NAME,
			STATE_US_ABBREVIATION,
			P0010001
		FROM US_COUNTIES_2010
		WHERE P0010001 >= 100000 )
SELECT ST,
	COUNT(*)
FROM LARGE_COUNTIES
GROUP BY ST
ORDER BY COUNT(*) DESC;